In [86]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geoapiExercises")

In [87]:
restaurant=pd.read_csv('Datafiniti_Fast_Food_Restaurants.csv')
restaurant_bt=pd.read_csv('just tacos and burritos.csv')

In [88]:
restaurant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10000 non-null  object
 1   dateAdded    10000 non-null  object
 2   dateUpdated  10000 non-null  object
 3   address      10000 non-null  object
 4   categories   10000 non-null  object
 5   city         10000 non-null  object
 6   country      10000 non-null  object
 7   keys         10000 non-null  object
 8   latitude     10000 non-null  float64
 9   longitude    10000 non-null  float64
 10  name         10000 non-null  object
 11  postalCode   10000 non-null  object
 12  province     10000 non-null  object
 13  sourceURLs   10000 non-null  object
 14  websites     10000 non-null  object
dtypes: float64(2), object(13)
memory usage: 1.1+ MB

In [89]:
restaurant_bt.dropna(how='all',axis=1,inplace=True)
restaurant_bt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77260 entries, 0 to 77259
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  77260 non-null  object
 1   address             77260 non-null  object
 2   categories          77260 non-null  object
 3   city                77260 non-null  object
 4   country             77260 non-null  object
 5   cuisines            38384 non-null  object
 6   dateAdded           77260 non-null  object
 7   dateUpdated         77260 non-null  object
 8   keys                77260 non-null  object
 9   latitude            55636 non-null  float64
 10  longitude           55636 non-null  float64
 11  menuPageURL         10054 non-null  object
 12  menus.amountMax     40260 non-null  float64
 13  menus.amountMin     40260 non-null  float64
 14  menus.category      3729 non-null   object
 15  menus.currency      40511 non-null  object
 16  menus.dateSeen      77260 non-null  object
 17  menus.description   29323 non-null  object
 18  menus.name          77260 non-null  object
 19  name                77257 non-null  object
 20  postalCode          76837 non-null  object
 21  priceRangeCurrency  48159 non-null  object
 22  priceRangeMin       48159 non-null  float64
 23  priceRangeMax       48159 non-null  float64
 24  province            77257 non-null  object
 25  websites            55989 non-null  object
dtypes: float64(6), object(20)
memory usage: 15.3+ MB

In [90]:
restaurant_bt

,id,address,categories,city,country,cuisines,dateAdded,dateUpdated,keys,latitude,...,menus.dateSeen,menus.description,menus.name,name,postalCode,priceRangeCurrency,priceRangeMin,priceRangeMax,province,websites
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,US,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,us/ks/atchison/610commercialst/-138126000,39.561570,...,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,66002,NaN,NaN,NaN,KS,http://www.gambinospizza.com
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,US,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,us/ks/atchison/610commercialst/-138126000,39.561570,...,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,66002,NaN,NaN,NaN,KS,http://www.gambinospizza.com
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,US,NaN,2016-10-14T01:58:25Z,2016-10-14T01:58:25Z,us/grayson/patterson/9521mortondavisdr/-522005016,37.401855,...,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,95363,NaN,NaN,NaN,Grayson,http://www.diablogrande.com/
3,AVwc__kCByjofQCxkdm-,10550 W I 25 Frontage Rd,Fast Food Restaurant,Longmont,US,NaN,2016-09-09T17:30:34Z,2016-10-04T05:15:17Z,us/niwot/longmont/10550wi25frontagerd/-1161002137,NaN,...,2016-09-09T17:30:34Z,NaN,Sausage Burrito,Mcdonald's,80504,NaN,NaN,NaN,Niwot,http://mcdonalds.com
4,AVwc__WtByjofQCxkdkR,8495 W 3rd St,"Mexican Restaurant Mid-City West,Mexican Resta...",Los Angeles,US,Mexican,2016-05-19T11:50:25Z,2016-09-11T00:06:37Z,us/bicentennial/losangeles/8495w3rdst/-251199537,34.080724,...,2016-05-19T11:50:25Z,"Wahoo, avocado, cabbage, pico de gallo and av...",Wahoo Tacogrilled,Baja Fresh Mexican Grill,90048,USD,0.0,25.0,Bicentennial,http://bajafresh.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77255,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,US,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,us/california/sanfrancisco/391924thst/-62682760,37.751392,...,2017-06-22T16:40:06.448Z,"meat, rice, beans, guacamole, sour cream, chee...",Super Burrito,La Casona Taqueria,94114-3703,NaN,NaN,NaN,California,NaN
77256,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,US,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,us/california/sanfrancisco/391924thst/-62682760,37.751392,...,2017-06-22T16:40:06.448Z,"melted cheese, rice, beans & salsa",Steamed Broccoli Burrito,La Casona Taqueria,94114-3703,NaN,NaN,NaN,California,NaN
77257,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,US,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,us/california/sanfrancisco/391924thst/-62682760,37.751392,...,2017-06-22T16:40:06.448Z,meat & salsa,Regular Taco,La Casona Taqueria,94114-3703,NaN,NaN,NaN,California,NaN
77258,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,US,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,us/california/sanfrancisco/391924thst/-62682760,37.751392,...,2017-06-22T16:40:06.448Z,"meat, rice, beans & salsa",Regular Burrito,La Casona Taqueria,94114-3703,NaN,NaN,NaN,California,NaN
77259,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,US,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,us/california/sanfrancisco/391924thst/-62682760,37.751392,...,2017-06-22T16:40:06.448Z,"stuffed with rice, beans, meat, topped with en...",Azteca Burrito,La Casona Taqueria,94114-3703,NaN,NaN,NaN,California,NaN

In [91]:
print(restaurant_bt['province'].value_counts())

CA                 23664
TX                  6099
FL                  2977
IL                  2725
AZ                  2355
                   ...
Stadium                1
Scituate Harbor        1
Woodcrest              1
Norland Park           1
Williston Pk           1
Name: province, Length: 1097, dtype: int64

In [92]:
restaurant_bt=restaurant_bt.dropna(subset=['latitude', 'longitude'],how='all')

In [93]:
restaurant_bt=restaurant_bt.drop_duplicates(subset=['id', 'address'], keep='first')
restaurant_bt.dropna(how='any',subset=['name'],axis=0,inplace=True)
restaurant_bt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14757 entries, 0 to 77250
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  14757 non-null  object
 1   address             14757 non-null  object
 2   categories          14757 non-null  object
 3   city                14757 non-null  object
 4   country             14757 non-null  object
 5   cuisines            9719 non-null   object
 6   dateAdded           14757 non-null  object
 7   dateUpdated         14757 non-null  object
 8   keys                14757 non-null  object
 9   latitude            14757 non-null  float64
 10  longitude           14757 non-null  float64
 11  menuPageURL         2602 non-null   object
 12  menus.amountMax     7548 non-null   float64
 13  menus.amountMin     7548 non-null   float64
 14  menus.category      1198 non-null   object
 15  menus.currency      7615 non-null   object
 16  menus.dateSeen      14757 non-null  object
 17  menus.description   6567 non-null   object
 18  menus.name          14757 non-null  object
 19  name                14757 non-null  object
 20  postalCode          14712 non-null  object
 21  priceRangeCurrency  9378 non-null   object
 22  priceRangeMin       9378 non-null   float64
 23  priceRangeMax       9378 non-null   float64
 24  province            14757 non-null  object
 25  websites            12890 non-null  object
dtypes: float64(6), object(20)
memory usage: 3.0+ MB

In [94]:
convert={'Alabama':'AL','Nebraska':'NE','Alaska':'AK','Nevada':'NV','Arizona':'AZ','New Hampshire':'NH','Arkansas':'AR','New Jersey':'NJ','California':'CA','New Mexico':'NM','Colorado':'CO','New York':'NY','Connecticut':'CT','North Carolina':'NC','Delaware':'DE','North Dakota':'ND','District of Columbia':'DC','Ohio':'OH','Florida':'FL','Oklahoma':'OK','Georgia':'GA','Oregon':'OR','Hawaii':'HI','Pennsylvania':'PA','Idaho':'ID','Puerto Rico':'PR','Illinois':'IL','Rhode Island':'RI','Indiana':'IN','South Carolina':'SC','Iowa':'IA','South Dakota':'SD','Kansas':'KS','Tennessee':'TN','Kentucky':'KY','Texas':'TX','Louisiana':'LA','Utah':'UT','Maine':'ME','Vermont':'VT','Maryland':'MD','Virginia':'VA','Massachusetts':'MA','Virgin Islands':'VI','Michigan':'MI','Washington':'WA','Minnesota':'MN','West Virginia':'WV','Mississippi':'MS','Wisconsin':'WI','Missouri':'MO','Wyoming':'WY','Montana':'MT'}

In [95]:
# province=[]
# for i in tqdm(range(len(restaurant_bt))):
#     lat=restaurant_bt.iloc[i]['latitude']
#     long=restaurant_bt.iloc[i]['longitude']
#     try:
#         results=geolocator.reverse(str(lat)+', '+str(long))
#         state=convert[results.raw['address']['state']]
#     except:
#         state=''
#     province.append(state)
# df.drop('province',inplace=True,axis=1)
# df['province']=province

In [96]:
restautrant_bt_new=restaurant_bt[['id','name','dateAdded','priceRangeMin','priceRangeMax','menus.name','websites','latitude','longitude','address','city','province','postalCode']]

In [97]:
restautrant_bt_new['taco_burrito']=[1 for i in range(len(restautrant_bt_new))]

<ipython-input-97-c87a7aa7ec37>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restautrant_bt_new['taco_burrito']=[1 for i in range(len(restautrant_bt_new))]

In [98]:
restautrant_bt_new

,id,name,dateAdded,priceRangeMin,priceRangeMax,menus.name,websites,latitude,longitude,address,city,province,postalCode,taco_burrito
0,AVwc__cikufWRAb51QjV,Gambino's Pizza,2016-03-02T11:49:34Z,NaN,NaN,Taco,http://www.gambinospizza.com,39.561570,-95.121020,610 Commercial St,Atchison,KS,66002,1
2,AVwc__dF_7pvs4fz1Ncy,Diablo Grande Golf & Country Club,2016-10-14T01:58:25Z,NaN,NaN,Smotherd Burrito,http://www.diablogrande.com/,37.401855,-121.266703,9521 Morton Davis Dr,Patterson,Grayson,95363,1
4,AVwc__WtByjofQCxkdkR,Baja Fresh Mexican Grill,2016-05-19T11:50:25Z,0.0,25.0,Wahoo Tacogrilled,http://bajafresh.com,34.080724,-118.389578,8495 W 3rd St,Los Angeles,Bicentennial,90048,1
15,AVwc_1y6kufWRAb51O6w,Java Joe's,2016-06-05T20:15:56Z,NaN,NaN,Mondo Veggie Burrito,http://downtownjavajoes.com,35.085320,-106.657616,906 Park Ave SW,Albuquerque,NM,87102,1
18,AVwc_2OQ_7pvs4fz1L5H,Mago Grill & Cantina - South Barrington,2016-07-26T17:39:41Z,0.0,30.0,Burrito De Rajas,http://www.magodining.com/,42.074974,-88.189151,100 W Higgins Rd,Barrington,Fox Rv Vly Gn,60010,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77235,AVzRLk2GFcQ3k02bBtCV,El Farolito,2017-06-22T19:01:31Z,NaN,NaN,Tacos,NaN,37.721270,-122.437410,4817 Mission St,San Francisco,California,94112-3413,1
77238,AVzRLkwULD2H7whiWdHX,Donna's Tamales,2017-06-22T19:01:31Z,NaN,NaN,Vegan Burrito,NaN,37.795403,-122.393814,1 Ferry Building,San Francisco,California,94111-4209,1
77245,AVzRLkyc-gnIPe8DS05C,Chevy's Fresh Mex,2017-06-22T19:01:31Z,NaN,NaN,Veggie Burrito,NaN,37.728510,-122.475570,3251 20th Ave Ste 182,San Francisco,California,94132-1918,1
77249,AVzRLlOl3D1zeR_xBVwZ,El Cafetazo,2017-06-22T19:01:33Z,NaN,NaN,Breakfast Burrito,NaN,37.764670,-122.421430,3087 16th St,San Francisco,California,94103-3420,1
77250,AVzRLlQNLD2H7whiWdH_,La Casona Taqueria,2017-06-22T19:01:33Z,NaN,NaN,Veggie Taco,NaN,37.751392,-122.430180,3919 24th St.,San Francisco,California,94114-3703,1

In [99]:
restaurant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10000 non-null  object
 1   dateAdded    10000 non-null  object
 2   dateUpdated  10000 non-null  object
 3   address      10000 non-null  object
 4   categories   10000 non-null  object
 5   city         10000 non-null  object
 6   country      10000 non-null  object
 7   keys         10000 non-null  object
 8   latitude     10000 non-null  float64
 9   longitude    10000 non-null  float64
 10  name         10000 non-null  object
 11  postalCode   10000 non-null  object
 12  province     10000 non-null  object
 13  sourceURLs   10000 non-null  object
 14  websites     10000 non-null  object
dtypes: float64(2), object(13)
memory usage: 1.1+ MB

In [100]:
restaurant_new=restaurant[['id','name','dateAdded','address','city','latitude','longitude','postalCode','province','websites']]

In [101]:
restaurant_new

,id,name,dateAdded,address,city,latitude,longitude,postalCode,province,websites
0,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,800 N Canal Blvd,Thibodaux,29.814697,-90.814742,70301,LA,https://locations.sonicdrivein.com/la/thibodau...
1,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,800 N Canal Blvd,Thibodaux,29.814697,-90.814742,70301,LA,https://locations.sonicdrivein.com/la/thibodau...
2,AVwcopQoByjofQCxgfVa,Taco Bell,2016-03-29T05:06:36Z,206 Wears Valley Rd,Pigeon Forge,35.803788,-83.580553,37863,TN,"http://www.tacobell.com,https://locations.taco..."
3,AVweXN5RByjofQCxxilK,Arby's,2017-01-03T07:46:11Z,3652 Parkway,Pigeon Forge,35.782339,-83.551408,37863,TN,"http://www.arbys.com,https://locations.arbys.c..."
4,AWQ6MUvo3-Khe5l_j3SG,Steak 'n Shake,2018-06-26T02:59:43Z,2118 Mt Zion Parkway,Morrow,33.562738,-84.321143,30260,GA,http://www.steaknshake.com/locations/23851-ste...
...,...,...,...,...,...,...,...,...,...,...
9995,AV12gJwna4HuVbed9Ayg,Pizza Hut,2017-07-24T21:28:46Z,3460 Robinhood Rd,Winston-Salem,36.117563,-80.316553,27106,NC,http://www.pizzahut.com
9996,AV12gJxKIxWefVJwhpzS,Pizza Hut,2017-07-24T21:28:46Z,3069 Kernersville Rd,Winston-Salem,36.077718,-80.176748,27107,NC,http://www.pizzahut.com
9997,AVwdJMdSByjofQCxl8Vr,Pizza Hut,2015-10-24T00:17:32Z,838 S Main St,Kernersville,36.111015,-80.089165,27284,NC,http://www.pizzahut.com
9998,AVwdl2cykufWRAb57ZPs,Pizza Hut,2016-04-05T02:59:45Z,1702 Glendale Dr SW,Wilson,35.719981,-77.945795,27893,NC,http://www.pizzahut.com
9999,AVwdecWKIN2L1WUfwMWU,Pizza Hut,2016-11-08T02:26:32Z,1405 W Broad St,Elizabethtown,34.632778,-78.624615,28337,NC,"http://www.pizzahut.com,http://api.citygridmed..."

In [102]:
restaurant_new['priceRangeMin']=np.nan
restaurant_new['priceRangeMax']=np.nan
restaurant_new['menuDesc']=np.nan
restaurant_new['flag']=[0 for i in range(len(restaurant_new))]

<ipython-input-102-02175d3c80c0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurant_new['priceRangeMin']=np.nan
<ipython-input-102-02175d3c80c0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurant_new['priceRangeMax']=np.nan
<ipython-input-102-02175d3c80c0>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurant_new['menuDesc']=np.nan
<ipython-input-102-02175d3c80c0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurant_new['flag']=[0 for i in range(len(restaurant_new))]

In [103]:
restaurant_new

,id,name,dateAdded,address,city,latitude,longitude,postalCode,province,websites,priceRangeMin,priceRangeMax,menuDesc,flag
0,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,800 N Canal Blvd,Thibodaux,29.814697,-90.814742,70301,LA,https://locations.sonicdrivein.com/la/thibodau...,NaN,NaN,NaN,0
1,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,800 N Canal Blvd,Thibodaux,29.814697,-90.814742,70301,LA,https://locations.sonicdrivein.com/la/thibodau...,NaN,NaN,NaN,0
2,AVwcopQoByjofQCxgfVa,Taco Bell,2016-03-29T05:06:36Z,206 Wears Valley Rd,Pigeon Forge,35.803788,-83.580553,37863,TN,"http://www.tacobell.com,https://locations.taco...",NaN,NaN,NaN,0
3,AVweXN5RByjofQCxxilK,Arby's,2017-01-03T07:46:11Z,3652 Parkway,Pigeon Forge,35.782339,-83.551408,37863,TN,"http://www.arbys.com,https://locations.arbys.c...",NaN,NaN,NaN,0
4,AWQ6MUvo3-Khe5l_j3SG,Steak 'n Shake,2018-06-26T02:59:43Z,2118 Mt Zion Parkway,Morrow,33.562738,-84.321143,30260,GA,http://www.steaknshake.com/locations/23851-ste...,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AV12gJwna4HuVbed9Ayg,Pizza Hut,2017-07-24T21:28:46Z,3460 Robinhood Rd,Winston-Salem,36.117563,-80.316553,27106,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9996,AV12gJxKIxWefVJwhpzS,Pizza Hut,2017-07-24T21:28:46Z,3069 Kernersville Rd,Winston-Salem,36.077718,-80.176748,27107,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9997,AVwdJMdSByjofQCxl8Vr,Pizza Hut,2015-10-24T00:17:32Z,838 S Main St,Kernersville,36.111015,-80.089165,27284,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9998,AVwdl2cykufWRAb57ZPs,Pizza Hut,2016-04-05T02:59:45Z,1702 Glendale Dr SW,Wilson,35.719981,-77.945795,27893,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9999,AVwdecWKIN2L1WUfwMWU,Pizza Hut,2016-11-08T02:26:32Z,1405 W Broad St,Elizabethtown,34.632778,-78.624615,28337,NC,"http://www.pizzahut.com,http://api.citygridmed...",NaN,NaN,NaN,0

In [104]:
restaurant_new=restaurant_new.rename(columns = {'flag':'taco_burrito'})
restaurant_new

,id,name,dateAdded,address,city,latitude,longitude,postalCode,province,websites,priceRangeMin,priceRangeMax,menuDesc,taco_burrito
0,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,800 N Canal Blvd,Thibodaux,29.814697,-90.814742,70301,LA,https://locations.sonicdrivein.com/la/thibodau...,NaN,NaN,NaN,0
1,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,800 N Canal Blvd,Thibodaux,29.814697,-90.814742,70301,LA,https://locations.sonicdrivein.com/la/thibodau...,NaN,NaN,NaN,0
2,AVwcopQoByjofQCxgfVa,Taco Bell,2016-03-29T05:06:36Z,206 Wears Valley Rd,Pigeon Forge,35.803788,-83.580553,37863,TN,"http://www.tacobell.com,https://locations.taco...",NaN,NaN,NaN,0
3,AVweXN5RByjofQCxxilK,Arby's,2017-01-03T07:46:11Z,3652 Parkway,Pigeon Forge,35.782339,-83.551408,37863,TN,"http://www.arbys.com,https://locations.arbys.c...",NaN,NaN,NaN,0
4,AWQ6MUvo3-Khe5l_j3SG,Steak 'n Shake,2018-06-26T02:59:43Z,2118 Mt Zion Parkway,Morrow,33.562738,-84.321143,30260,GA,http://www.steaknshake.com/locations/23851-ste...,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AV12gJwna4HuVbed9Ayg,Pizza Hut,2017-07-24T21:28:46Z,3460 Robinhood Rd,Winston-Salem,36.117563,-80.316553,27106,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9996,AV12gJxKIxWefVJwhpzS,Pizza Hut,2017-07-24T21:28:46Z,3069 Kernersville Rd,Winston-Salem,36.077718,-80.176748,27107,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9997,AVwdJMdSByjofQCxl8Vr,Pizza Hut,2015-10-24T00:17:32Z,838 S Main St,Kernersville,36.111015,-80.089165,27284,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9998,AVwdl2cykufWRAb57ZPs,Pizza Hut,2016-04-05T02:59:45Z,1702 Glendale Dr SW,Wilson,35.719981,-77.945795,27893,NC,http://www.pizzahut.com,NaN,NaN,NaN,0
9999,AVwdecWKIN2L1WUfwMWU,Pizza Hut,2016-11-08T02:26:32Z,1405 W Broad St,Elizabethtown,34.632778,-78.624615,28337,NC,"http://www.pizzahut.com,http://api.citygridmed...",NaN,NaN,NaN,0

In [105]:
restautrant_bt_new=restautrant_bt_new.rename(columns = {'menus.name':'menuDesc'})

In [106]:
restaurant_new=restaurant_new[restautrant_bt_new.columns]
restaurant_new

,id,name,dateAdded,priceRangeMin,priceRangeMax,menuDesc,websites,latitude,longitude,address,city,province,postalCode,taco_burrito
0,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,NaN,NaN,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,800 N Canal Blvd,Thibodaux,LA,70301,0
1,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,NaN,NaN,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,800 N Canal Blvd,Thibodaux,LA,70301,0
2,AVwcopQoByjofQCxgfVa,Taco Bell,2016-03-29T05:06:36Z,NaN,NaN,NaN,"http://www.tacobell.com,https://locations.taco...",35.803788,-83.580553,206 Wears Valley Rd,Pigeon Forge,TN,37863,0
3,AVweXN5RByjofQCxxilK,Arby's,2017-01-03T07:46:11Z,NaN,NaN,NaN,"http://www.arbys.com,https://locations.arbys.c...",35.782339,-83.551408,3652 Parkway,Pigeon Forge,TN,37863,0
4,AWQ6MUvo3-Khe5l_j3SG,Steak 'n Shake,2018-06-26T02:59:43Z,NaN,NaN,NaN,http://www.steaknshake.com/locations/23851-ste...,33.562738,-84.321143,2118 Mt Zion Parkway,Morrow,GA,30260,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AV12gJwna4HuVbed9Ayg,Pizza Hut,2017-07-24T21:28:46Z,NaN,NaN,NaN,http://www.pizzahut.com,36.117563,-80.316553,3460 Robinhood Rd,Winston-Salem,NC,27106,0
9996,AV12gJxKIxWefVJwhpzS,Pizza Hut,2017-07-24T21:28:46Z,NaN,NaN,NaN,http://www.pizzahut.com,36.077718,-80.176748,3069 Kernersville Rd,Winston-Salem,NC,27107,0
9997,AVwdJMdSByjofQCxl8Vr,Pizza Hut,2015-10-24T00:17:32Z,NaN,NaN,NaN,http://www.pizzahut.com,36.111015,-80.089165,838 S Main St,Kernersville,NC,27284,0
9998,AVwdl2cykufWRAb57ZPs,Pizza Hut,2016-04-05T02:59:45Z,NaN,NaN,NaN,http://www.pizzahut.com,35.719981,-77.945795,1702 Glendale Dr SW,Wilson,NC,27893,0
9999,AVwdecWKIN2L1WUfwMWU,Pizza Hut,2016-11-08T02:26:32Z,NaN,NaN,NaN,"http://www.pizzahut.com,http://api.citygridmed...",34.632778,-78.624615,1405 W Broad St,Elizabethtown,NC,28337,0

In [107]:
frames=[restaurant_new,restautrant_bt_new]
bigTable=pd.concat(frames)

In [108]:
bigTable

,id,name,dateAdded,priceRangeMin,priceRangeMax,menuDesc,websites,latitude,longitude,address,city,province,postalCode,taco_burrito
0,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,NaN,NaN,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,800 N Canal Blvd,Thibodaux,LA,70301,0
1,AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,NaN,NaN,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,800 N Canal Blvd,Thibodaux,LA,70301,0
2,AVwcopQoByjofQCxgfVa,Taco Bell,2016-03-29T05:06:36Z,NaN,NaN,NaN,"http://www.tacobell.com,https://locations.taco...",35.803788,-83.580553,206 Wears Valley Rd,Pigeon Forge,TN,37863,0
3,AVweXN5RByjofQCxxilK,Arby's,2017-01-03T07:46:11Z,NaN,NaN,NaN,"http://www.arbys.com,https://locations.arbys.c...",35.782339,-83.551408,3652 Parkway,Pigeon Forge,TN,37863,0
4,AWQ6MUvo3-Khe5l_j3SG,Steak 'n Shake,2018-06-26T02:59:43Z,NaN,NaN,NaN,http://www.steaknshake.com/locations/23851-ste...,33.562738,-84.321143,2118 Mt Zion Parkway,Morrow,GA,30260,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77235,AVzRLk2GFcQ3k02bBtCV,El Farolito,2017-06-22T19:01:31Z,NaN,NaN,Tacos,NaN,37.721270,-122.437410,4817 Mission St,San Francisco,California,94112-3413,1
77238,AVzRLkwULD2H7whiWdHX,Donna's Tamales,2017-06-22T19:01:31Z,NaN,NaN,Vegan Burrito,NaN,37.795403,-122.393814,1 Ferry Building,San Francisco,California,94111-4209,1
77245,AVzRLkyc-gnIPe8DS05C,Chevy's Fresh Mex,2017-06-22T19:01:31Z,NaN,NaN,Veggie Burrito,NaN,37.728510,-122.475570,3251 20th Ave Ste 182,San Francisco,California,94132-1918,1
77249,AVzRLlOl3D1zeR_xBVwZ,El Cafetazo,2017-06-22T19:01:33Z,NaN,NaN,Breakfast Burrito,NaN,37.764670,-122.421430,3087 16th St,San Francisco,California,94103-3420,1
77250,AVzRLlQNLD2H7whiWdH_,La Casona Taqueria,2017-06-22T19:01:33Z,NaN,NaN,Veggie Taco,NaN,37.751392,-122.430180,3919 24th St.,San Francisco,California,94114-3703,1

In [109]:
bigTable=bigTable.drop_duplicates(subset=['id', 'address'], keep='first')

In [110]:
val=[np.nan if np.isnan(bigTable.iloc[i]['priceRangeMin']) else (bigTable.iloc[i]['priceRangeMin']+bigTable.iloc[i]['priceRangeMax'])/2 for i in range(len(bigTable))]

In [111]:
bigTable['priceRangeAvg']=val

<ipython-input-111-e18ebe9e8848>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigTable['priceRangeAvg']=val

In [112]:
bigTable=bigTable.drop_duplicates(subset=['id'], keep='first')
bigTable.set_index('id',inplace=True)

In [120]:
indexa = bigTable[bigTable.priceRangeAvg.isna()].index
value = np.random.normal(loc=bigTable.priceRangeAvg.mean(), scale=bigTable.priceRangeAvg.std(), size=bigTable.priceRangeAvg.isna().sum())
value=np.array(list(map(lambda x: abs(x)+2, value)))
bigTable.priceRangeAvg.fillna(pd.Series(value, index=indexa), inplace=True)

In [121]:
bigTable

,name,dateAdded,priceRangeMin,priceRangeMax,menuDesc,websites,latitude,longitude,address,city,province,postalCode,taco_burrito,priceRangeAvg
id,,,,,,,,,,,,,,
AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,NaN,NaN,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,800 N Canal Blvd,Thibodaux,LA,70301,0,4.015587
AVwcopQoByjofQCxgfVa,Taco Bell,2016-03-29T05:06:36Z,NaN,NaN,NaN,"http://www.tacobell.com,https://locations.taco...",35.803788,-83.580553,206 Wears Valley Rd,Pigeon Forge,TN,37863,0,9.075665
AVweXN5RByjofQCxxilK,Arby's,2017-01-03T07:46:11Z,NaN,NaN,NaN,"http://www.arbys.com,https://locations.arbys.c...",35.782339,-83.551408,3652 Parkway,Pigeon Forge,TN,37863,0,22.831414
AWQ6MUvo3-Khe5l_j3SG,Steak 'n Shake,2018-06-26T02:59:43Z,NaN,NaN,NaN,http://www.steaknshake.com/locations/23851-ste...,33.562738,-84.321143,2118 Mt Zion Parkway,Morrow,GA,30260,0,53.828380
AVwc57jLkufWRAb50ROs,Wendy's,2015-10-23T23:59:49Z,NaN,NaN,NaN,http://www.wendys.com,42.368823,-83.138251,9768 Grand River Ave,Detroit,MI,48204,0,37.052997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AVzRLk2GFcQ3k02bBtCV,El Farolito,2017-06-22T19:01:31Z,NaN,NaN,Tacos,NaN,37.721270,-122.437410,4817 Mission St,San Francisco,California,94112-3413,1,29.803121
AVzRLkwULD2H7whiWdHX,Donna's Tamales,2017-06-22T19:01:31Z,NaN,NaN,Vegan Burrito,NaN,37.795403,-122.393814,1 Ferry Building,San Francisco,California,94111-4209,1,20.046121
AVzRLkyc-gnIPe8DS05C,Chevy's Fresh Mex,2017-06-22T19:01:31Z,NaN,NaN,Veggie Burrito,NaN,37.728510,-122.475570,3251 20th Ave Ste 182,San Francisco,California,94132-1918,1,37.932882
AVzRLlOl3D1zeR_xBVwZ,El Cafetazo,2017-06-22T19:01:33Z,NaN,NaN,Breakfast Burrito,NaN,37.764670,-122.421430,3087 16th St,San Francisco,California,94103-3420,1,10.082888
AVzRLlQNLD2H7whiWdH_,La Casona Taqueria,2017-06-22T19:01:33Z,NaN,NaN,Veggie Taco,NaN,37.751392,-122.430180,3919 24th St.,San Francisco,California,94114-3703,1,9.553835

In [122]:
bigTable['priceRangeAvg']=bigTable['priceRangeAvg'].apply(lambda x:round(x))

In [123]:
bigTable['avgReview']=np.nan

In [124]:
bigTable=bigTable[bigTable['province'].isin(convert.values())]

In [125]:
cityProv=bigTable[['city','province']]

In [126]:
cityProv

                              city province
id
AVwcmSyZIN2L1WUfmxyw     Thibodaux       LA
AVwcopQoByjofQCxgfVa  Pigeon Forge       TN
AVweXN5RByjofQCxxilK  Pigeon Forge       TN
AWQ6MUvo3-Khe5l_j3SG        Morrow       GA
AVwc57jLkufWRAb50ROs       Detroit       MI
...                            ...      ...
AVz0WYK2-gnIPe8DUW4J        Dallas       TX
AVz0WZ18FcQ3k02bDO8m   Weatherford       TX
AVz0WZf3-gnIPe8DUW4y     Mansfield       TX
AVz0WZjfFcQ3k02bDO8a    Little Elm       TX
AVz0WZsS-gnIPe8DUW45        Irving       TX

[21749 rows x 2 columns]

In [127]:
bigTable['cityId']=np.nan
cityProv['cityId']=np.nan
dict_helper={}
index=0
l=bigTable.index.to_list()
for i in l:
    try:
        bigTable.at[i,'cityId']=dict_helper[cityProv.at[i,'city']+cityProv.at[i,'province']]
        cityProv.at[i,'cityId']=dict_helper[cityProv.at[i,'city']+cityProv.at[i,'province']]
    except:
        index+=1
        dict_helper[cityProv.at[i,'city']+cityProv.at[i,'province']]=index
        bigTable.at[i,'cityId']=index
        cityProv.at[i,'cityId']=index

<ipython-input-127-17efe48cc41f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigTable['cityId']=np.nan
<ipython-input-127-17efe48cc41f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cityProv['cityId']=np.nan

In [128]:
cityProv['cityId']=cityProv['cityId'].apply(lambda x: int(x))
bigTable['cityId']=bigTable['cityId'].apply(lambda x: int(x))

<ipython-input-128-f6c06de10505>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cityProv['cityId']=cityProv['cityId'].apply(lambda x: int(x))
<ipython-input-128-f6c06de10505>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigTable['cityId']=bigTable['cityId'].apply(lambda x: int(x))

In [129]:
cityProv

                              city province  cityId
id
AVwcmSyZIN2L1WUfmxyw     Thibodaux       LA       1
AVwcopQoByjofQCxgfVa  Pigeon Forge       TN       2
AVweXN5RByjofQCxxilK  Pigeon Forge       TN       2
AWQ6MUvo3-Khe5l_j3SG        Morrow       GA       3
AVwc57jLkufWRAb50ROs       Detroit       MI       4
...                            ...      ...     ...
AVz0WYK2-gnIPe8DUW4J        Dallas       TX     806
AVz0WZ18FcQ3k02bDO8m   Weatherford       TX     856
AVz0WZf3-gnIPe8DUW4y     Mansfield       TX    2873
AVz0WZjfFcQ3k02bDO8a    Little Elm       TX     356
AVz0WZsS-gnIPe8DUW45        Irving       TX    1955

[21749 rows x 3 columns]

In [130]:
cityProv.drop_duplicates(subset=['cityId'], keep='first',inplace=True)

<ipython-input-130-61bd3dcb2aaf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cityProv.drop_duplicates(subset=['cityId'], keep='first',inplace=True)

In [131]:
cityProv.set_index('cityId',inplace=True)

In [132]:
cityProv

                  city province
cityId
1            Thibodaux       LA
2         Pigeon Forge       TN
3               Morrow       GA
4              Detroit       MI
5            Oceanside       CA
...                ...      ...
4938          Eldridge       IA
4939         Dadeville       AL
4940            Oxford       NC
4941        Burlington       KS
4942    San Tan Valley       AZ

[4942 rows x 2 columns]

In [133]:
province=pd.DataFrame(list(convert.items()),columns = ['name','provinceId']) 
province.set_index('provinceId',inplace=True)

In [134]:
province

                            name
provinceId
AL                       Alabama
NE                      Nebraska
AK                        Alaska
NV                        Nevada
AZ                       Arizona
NH                 New Hampshire
AR                      Arkansas
NJ                    New Jersey
CA                    California
NM                    New Mexico
CO                      Colorado
NY                      New York
CT                   Connecticut
NC                North Carolina
DE                      Delaware
ND                  North Dakota
DC          District of Columbia
OH                          Ohio
FL                       Florida
OK                      Oklahoma
GA                       Georgia
OR                        Oregon
HI                        Hawaii
PA                  Pennsylvania
ID                         Idaho
PR                   Puerto Rico
IL                      Illinois
RI                  Rhode Island
IN                       Indiana
SC                South Carolina
IA                          Iowa
SD                  South Dakota
KS                        Kansas
TN                     Tennessee
KY                      Kentucky
TX                         Texas
LA                     Louisiana
UT                          Utah
ME                         Maine
VT                       Vermont
MD                      Maryland
VA                      Virginia
MA                 Massachusetts
VI                Virgin Islands
MI                      Michigan
WA                    Washington
MN                     Minnesota
WV                 West Virginia
MS                   Mississippi
WI                     Wisconsin
MO                      Missouri
WY                       Wyoming
MT                       Montana

In [135]:
bigTable

,name,dateAdded,priceRangeMin,priceRangeMax,menuDesc,websites,latitude,longitude,address,city,province,postalCode,taco_burrito,priceRangeAvg,avgReview,cityId
id,,,,,,,,,,,,,,,,
AVwcmSyZIN2L1WUfmxyw,SONIC Drive In,2015-10-19T23:47:58Z,NaN,NaN,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,800 N Canal Blvd,Thibodaux,LA,70301,0,4,NaN,1
AVwcopQoByjofQCxgfVa,Taco Bell,2016-03-29T05:06:36Z,NaN,NaN,NaN,"http://www.tacobell.com,https://locations.taco...",35.803788,-83.580553,206 Wears Valley Rd,Pigeon Forge,TN,37863,0,9,NaN,2
AVweXN5RByjofQCxxilK,Arby's,2017-01-03T07:46:11Z,NaN,NaN,NaN,"http://www.arbys.com,https://locations.arbys.c...",35.782339,-83.551408,3652 Parkway,Pigeon Forge,TN,37863,0,23,NaN,2
AWQ6MUvo3-Khe5l_j3SG,Steak 'n Shake,2018-06-26T02:59:43Z,NaN,NaN,NaN,http://www.steaknshake.com/locations/23851-ste...,33.562738,-84.321143,2118 Mt Zion Parkway,Morrow,GA,30260,0,54,NaN,3
AVwc57jLkufWRAb50ROs,Wendy's,2015-10-23T23:59:49Z,NaN,NaN,NaN,http://www.wendys.com,42.368823,-83.138251,9768 Grand River Ave,Detroit,MI,48204,0,37,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AVz0WYK2-gnIPe8DUW4J,Chino Chinatown at Trinity Groves,2017-06-29T14:55:25Z,0.0,30.0,Dover Sole Taco,http://www.chinochinatown.com/,32.779388,-96.828367,3011 Gulden Lane Suite 110,Dallas,TX,75212,1,15,NaN,806
AVz0WZ18FcQ3k02bDO8m,Los Vaqueros - West,2017-06-29T14:55:32Z,0.0,30.0,Tacos al Carbon,http://www.losvaqueros.com/,32.752010,-97.669332,29 Crown Rd.Building B,Weatherford,TX,76087,1,15,NaN,856
AVz0WZf3-gnIPe8DUW4y,El Primo's Mexican Grill & Cantina,2017-06-29T14:55:31Z,0.0,30.0,Ensalada Taco,http://www.elprimos.net/,32.594093,-97.106282,2300 Matlock Rd. Suite 21,Mansfield,TX,76063,1,15,NaN,2873
AVz0WZjfFcQ3k02bDO8a,Hula Hut,2017-06-29T14:55:31Z,0.0,30.0,Veggie Tubular Taco,http://hulahut.com/,33.161393,-96.936651,201 E. Eldorado Pkwy,Little Elm,TX,75068,1,15,NaN,356
AVz0WZsS-gnIPe8DUW45,LAW at Four Seasons Dallas,2017-06-29T14:55:32Z,31.0,50.0,Beer Can Chicken Tacos,http://www.lawrestaurant.com/,32.862452,-96.959246,4150 North MacArthur Blvd,Irving,TX,75038,1,40,NaN,1955

In [136]:
restId=[i for i in range(1,len(bigTable)+1)]
bigTable['restId']=restId
bigTable.set_index('restId',inplace=True)

<ipython-input-136-c0fe396a9d66>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigTable['restId']=restId

In [137]:
bigTable

,name,dateAdded,priceRangeMin,priceRangeMax,menuDesc,websites,latitude,longitude,address,city,province,postalCode,taco_burrito,priceRangeAvg,avgReview,cityId
restId,,,,,,,,,,,,,,,,
1,SONIC Drive In,2015-10-19T23:47:58Z,NaN,NaN,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,800 N Canal Blvd,Thibodaux,LA,70301,0,4,NaN,1
2,Taco Bell,2016-03-29T05:06:36Z,NaN,NaN,NaN,"http://www.tacobell.com,https://locations.taco...",35.803788,-83.580553,206 Wears Valley Rd,Pigeon Forge,TN,37863,0,9,NaN,2
3,Arby's,2017-01-03T07:46:11Z,NaN,NaN,NaN,"http://www.arbys.com,https://locations.arbys.c...",35.782339,-83.551408,3652 Parkway,Pigeon Forge,TN,37863,0,23,NaN,2
4,Steak 'n Shake,2018-06-26T02:59:43Z,NaN,NaN,NaN,http://www.steaknshake.com/locations/23851-ste...,33.562738,-84.321143,2118 Mt Zion Parkway,Morrow,GA,30260,0,54,NaN,3
5,Wendy's,2015-10-23T23:59:49Z,NaN,NaN,NaN,http://www.wendys.com,42.368823,-83.138251,9768 Grand River Ave,Detroit,MI,48204,0,37,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21745,Chino Chinatown at Trinity Groves,2017-06-29T14:55:25Z,0.0,30.0,Dover Sole Taco,http://www.chinochinatown.com/,32.779388,-96.828367,3011 Gulden Lane Suite 110,Dallas,TX,75212,1,15,NaN,806
21746,Los Vaqueros - West,2017-06-29T14:55:32Z,0.0,30.0,Tacos al Carbon,http://www.losvaqueros.com/,32.752010,-97.669332,29 Crown Rd.Building B,Weatherford,TX,76087,1,15,NaN,856
21747,El Primo's Mexican Grill & Cantina,2017-06-29T14:55:31Z,0.0,30.0,Ensalada Taco,http://www.elprimos.net/,32.594093,-97.106282,2300 Matlock Rd. Suite 21,Mansfield,TX,76063,1,15,NaN,2873
21748,Hula Hut,2017-06-29T14:55:31Z,0.0,30.0,Veggie Tubular Taco,http://hulahut.com/,33.161393,-96.936651,201 E. Eldorado Pkwy,Little Elm,TX,75068,1,15,NaN,356
21749,LAW at Four Seasons Dallas,2017-06-29T14:55:32Z,31.0,50.0,Beer Can Chicken Tacos,http://www.lawrestaurant.com/,32.862452,-96.959246,4150 North MacArthur Blvd,Irving,TX,75038,1,40,NaN,1955

In [138]:
bigTable['dateAdded']=bigTable['dateAdded'].apply(lambda x: x[:10])

<ipython-input-138-3208dcdd3d7c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigTable['dateAdded']=bigTable['dateAdded'].apply(lambda x: x[:10])

In [140]:
bigTable_n=bigTable[['name','dateAdded','menuDesc','websites','latitude','longitude','cityId','address','postalCode','taco_burrito','priceRangeAvg','avgReview']]

In [141]:
bigTable_n

,name,dateAdded,menuDesc,websites,latitude,longitude,cityId,address,postalCode,taco_burrito,priceRangeAvg,avgReview
restId,,,,,,,,,,,,
1,SONIC Drive In,2015-10-19,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,1,800 N Canal Blvd,70301,0,4,NaN
2,Taco Bell,2016-03-29,NaN,"http://www.tacobell.com,https://locations.taco...",35.803788,-83.580553,2,206 Wears Valley Rd,37863,0,9,NaN
3,Arby's,2017-01-03,NaN,"http://www.arbys.com,https://locations.arbys.c...",35.782339,-83.551408,2,3652 Parkway,37863,0,23,NaN
4,Steak 'n Shake,2018-06-26,NaN,http://www.steaknshake.com/locations/23851-ste...,33.562738,-84.321143,3,2118 Mt Zion Parkway,30260,0,54,NaN
5,Wendy's,2015-10-23,NaN,http://www.wendys.com,42.368823,-83.138251,4,9768 Grand River Ave,48204,0,37,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
21745,Chino Chinatown at Trinity Groves,2017-06-29,Dover Sole Taco,http://www.chinochinatown.com/,32.779388,-96.828367,806,3011 Gulden Lane Suite 110,75212,1,15,NaN
21746,Los Vaqueros - West,2017-06-29,Tacos al Carbon,http://www.losvaqueros.com/,32.752010,-97.669332,856,29 Crown Rd.Building B,76087,1,15,NaN
21747,El Primo's Mexican Grill & Cantina,2017-06-29,Ensalada Taco,http://www.elprimos.net/,32.594093,-97.106282,2873,2300 Matlock Rd. Suite 21,76063,1,15,NaN
21748,Hula Hut,2017-06-29,Veggie Tubular Taco,http://hulahut.com/,33.161393,-96.936651,356,201 E. Eldorado Pkwy,75068,1,15,NaN
21749,LAW at Four Seasons Dallas,2017-06-29,Beer Can Chicken Tacos,http://www.lawrestaurant.com/,32.862452,-96.959246,1955,4150 North MacArthur Blvd,75038,1,40,NaN

In [151]:
def random_phone_num_generator():
    first = str(random.randint(100, 999))
    second = str(random.randint(1, 888)).zfill(3)
    last = (str(random.randint(1, 9998)).zfill(4))
    while last in ['1111', '2222', '3333', '4444', '5555', '6666', '7777', '8888']:
        last = (str(random.randint(1, 9998)).zfill(4))
    return '({})-{}-{}'.format(first, second, last)
phone=[random_phone_num_generator() for i in range(len(bigTable_n))]
bigTable_n['phoneNo']=phone

<ipython-input-151-e0ea5d81ec97>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigTable_n['phoneNo']=phone

In [152]:
bigTable_n

,name,dateAdded,menuDesc,websites,latitude,longitude,cityId,address,postalCode,taco_burrito,priceRangeAvg,avgReview,phoneNo
restId,,,,,,,,,,,,,
1,SONIC Drive In,2015-10-19,NaN,https://locations.sonicdrivein.com/la/thibodau...,29.814697,-90.814742,1,800 N Canal Blvd,70301,0,4,NaN,(879)-319-4791
2,Taco Bell,2016-03-29,NaN,"http://www.tacobell.com,https://locations.taco...",35.803788,-83.580553,2,206 Wears Valley Rd,37863,0,9,NaN,(153)-686-1489
3,Arby's,2017-01-03,NaN,"http://www.arbys.com,https://locations.arbys.c...",35.782339,-83.551408,2,3652 Parkway,37863,0,23,NaN,(326)-094-6390
4,Steak 'n Shake,2018-06-26,NaN,http://www.steaknshake.com/locations/23851-ste...,33.562738,-84.321143,3,2118 Mt Zion Parkway,30260,0,54,NaN,(195)-489-6920
5,Wendy's,2015-10-23,NaN,http://www.wendys.com,42.368823,-83.138251,4,9768 Grand River Ave,48204,0,37,NaN,(153)-882-2604
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21745,Chino Chinatown at Trinity Groves,2017-06-29,Dover Sole Taco,http://www.chinochinatown.com/,32.779388,-96.828367,806,3011 Gulden Lane Suite 110,75212,1,15,NaN,(234)-092-1080
21746,Los Vaqueros - West,2017-06-29,Tacos al Carbon,http://www.losvaqueros.com/,32.752010,-97.669332,856,29 Crown Rd.Building B,76087,1,15,NaN,(577)-469-8362
21747,El Primo's Mexican Grill & Cantina,2017-06-29,Ensalada Taco,http://www.elprimos.net/,32.594093,-97.106282,2873,2300 Matlock Rd. Suite 21,76063,1,15,NaN,(603)-801-6358
21748,Hula Hut,2017-06-29,Veggie Tubular Taco,http://hulahut.com/,33.161393,-96.936651,356,201 E. Eldorado Pkwy,75068,1,15,NaN,(510)-875-2177
21749,LAW at Four Seasons Dallas,2017-06-29,Beer Can Chicken Tacos,http://www.lawrestaurant.com/,32.862452,-96.959246,1955,4150 North MacArthur Blvd,75038,1,40,NaN,(648)-813-5921